version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: web/backend/Dockerfile
    container_name: gpx-art-backend
    restart: unless-stopped
    volumes:
      - backend_uploads:/app/uploads
      - backend_output:/app/output
      - backend_logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - ENV=development
      - DEBUG=false
      - LOG_LEVEL=INFO
      - API_VERSION=1.0.0
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      - MAX_UPLOAD_SIZE=10485760
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - gpx-art-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gpx-art-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - NODE_ENV=development
    networks:
      - gpx-art-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  backend_uploads:
    driver: local
  backend_output:
    driver: local
  backend_logs:
    driver: local

networks:
  gpx-art-network:
    driver: bridge

